# Generated by Django 4.0.3 on 2022-03-12 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('audience_number', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='Номер аудитории')),
                ('description', models.CharField(max_length=128, verbose_name='Описание')),
                ('capacity', models.CharField(max_length=64, verbose_name='вместимость(чел)')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=128, verbose_name='ФИО')),
                ('category', models.IntegerField(choices=[(1, 'Студент'), (2, 'Преподаватель'), (3, 'Сотрудник')], verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала брони')),
                ('reservation_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания брони')),
                ('audience_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.room', verbose_name='Номер аудитории')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=64, verbose_name='Наименование оборудования')),
                ('number', models.IntegerField(verbose_name='Кол-во оборудования в аудитории')),
                ('audience_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.room', verbose_name='Номер аудитории')),
            ],
        ),
    ]
